---
# handlers file for devopsrob.lampapache
- name: restart_services
  service:
    name: "{{ item }}"
    state: restarted
  with_items: "{{ system_services }}"

- name: start_lamp
  service:
    name: "{{ item }}"
    state: restarted
  with_items: "{{ ubuntu_services }}"